pipeline {
    agent {
        label 'AGENT-1'
    }

    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "607700977716"
        PROJECT = "roboshop"
        STATE_BUCKET = "dawst-remote-state"
        STATE_KEY = "roboshop-dev-ingress-alb"
    }

    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: "${REGION}") {
                        sh """
                            cd 70-frontend-alb
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('unlock-if-needed') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: "${REGION}") {
                        sh """
                            cd 70-frontend-alb
                            # Check if lock file exists in S3
                            if aws s3 ls s3://$STATE_BUCKET/$STATE_KEY.tflock >/dev/null 2>&1; then
                                echo "Terraform lock file found in S3, forcing unlock..."
                                # Try unlocking with a random UUID (Terraform ignores if ID doesn't match)
                                terraform force-unlock -force \$(uuidgen) || true
                            else
                                echo "No lock file exists in S3, skipping unlock"
                            fi
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: "${REGION}") {
                        sh """
                            cd 70-frontend-alb
                            terraform plan -input=false
                        """
                    }
                }
            }
        }

        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: "${REGION}") {
                        sh """
                            cd 70-frontend-alb
                            terraform apply -input=false -auto-approve || exit 1
                        """
                    }
                }
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            sh 'cat 70-frontend-alb/terraform.tfstate || true'
            echo 'Hello Failure'
        }
    }
}
