pipeline {
    agent {
        label 'AGENT-1'
    }

    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "607700977716"
        PROJECT = "roboshop"
    }

    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 70-frontend-alb
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }

        stage('unlock') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 70-frontend-alb
                            # Force unlock any stale state lock (ignore errors if no lock)
                            terraform force-unlock -force 0d15b7a5-d530-3490-a519-5ee3d46d586f || true
                        """
                    }
                }
            }
        }

        stage('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 70-frontend-alb
                            terraform plan -input=false
                        """
                    }
                }
            }
        }

        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 70-frontend-alb
                            terraform apply -input=false -auto-approve || exit 1
                        """
                    }
                }
            }
        }
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            sh 'cat 70-frontend-alb/terraform.tfstate || true'
            echo 'Hello Failure'
        }
    }
}
